language: node_js
node_js:
  - '7'
  - '6'
  - '4'
cache:
  directories:
    - $HOME/.npm
    - node_modules
before_install: 'npm install --global npm'
before_script: 'npm prune'
script: 'npm run coverage'
after_script: './node_modules/.bin/codecov --file=./coverage/lcov.info'
